---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git

# homebrew cask applications
cask_applications:
  - google-chrome
