---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - vim

# homebrew cask applications
cask_applications:
  - google-chrome
  - slack
  - intellij-idea
  - sublime-text
  - java
  - maven
